### ISSUE TITLE
Zany80 crashes after using the "reset" command in the terminal

### ISSUE THREAD

**Issue by Uberoverlord** [Zany80/Zany80#1]

**Comment by pixelherodev** [comment]
With the latest build? Can you paste the log here?

**Comment by Uberoverlord** [comment]
![image](https://user-images.githubusercontent.com/8922939/39159077-8554ce7c-4718-11e8-84bb-5f4de747ca65.png)
This is on the latest version and is all of the information I receive on the crash.

**Comment by pixelherodev** [comment]
This is a Windows-specific bug. I don't have time to look into it right now, if you remind me in ~2 weeks I should be able to work on it.

**Comment by pixelherodev** [comment]
I'm going to investigate the Windows-specific issues later today.

**Comment by pixelherodev** [comment]
Confirmed to cause a segfault.
