### ISSUE TITLE
After assembling a ROM with the builtin tools it is incompatible

### ISSUE THREAD

**Issue by Uberoverlord** [Zany80/Zany80#4]
I have a file containing only the halt instruction. It assembles just fine but once there is an attempt to run it it says that it is an incompatible ROM. To assemble I am using `assemble file.asm -o file.rom` as previously told would work in Discord.

**Comment by pixelherodev** [comment]
Ah, sorry about the confusion (and late delay). This isn't actually a bug, I have changed the way the OS loads in programs.

I'm going to push an update momentarily - this will be 0.1.0 (there were two or three more features planned, but they aren't essential and I have a _week_ to finish an extremely urgent project IRL. Try assembling 
```z80
_rom_name:
    .asciiz "Hello, world!"
_main:
    ld b, 60
.loop:
    ; wait for vsync
    halt
    ; clear the screen
    ld a, 0
    ld b, 0
    call 0x8000
    djnz .loop
    ret
```

with `assemble file.asm -c -o file.o` 
`link file.o -o file.rom --embed --link-crt`

`--embed` can be replaced with `-e`, `--link-crt` can be replaced with `-c`, but `-ce` or `-ec` won't work yet (feel free to file that as a bug also).

**Comment by pixelherodev** [comment]
Actually wait, the `-c`/`--link-crt` isn't needed.
