### ISSUE TITLE
Zany's window stretches the display

### ISSUE THREAD

**Issue by Uberoverlord** [Zany80/Zany80#8]
Zany's display window has an inconsistent aspect ratio and can the window can be stretched in sizes where the display is stretched out in one direction more than others. The window also begins too small for the font to properly be rendered, making resizing necessary. This is especially a problem in many tiled window managers where you are almost guaranteed a stretched display.

**Comment by pixelherodev** [comment]
Moving the current state of this repo to a new branch labelled "old" for archival reasons only. This bug does not affect the new code base, so is being closed.
